In [9]:
! ls ../pytn
import sys
sys.path.append("..")

__init__.py   ctmrg_test.py mpo.py        mps_test.py
__pycache__   dmrg.py       mpo_test.py   utils.py
ctmrg.py      dmrg_test.py  mps.py


In [65]:
import importlib
import pytn
import pytn.mpo
importlib.reload(pytn.mpo)

<module 'pytn.mpo' from '../pytn/mpo.py'>

In [73]:
num = 2
mpo = pytn.mpo.traverse_field_ising_mpo(J=2.0, g=0.0, num=num)
m = mpo.as_matrix()
t = mpo.full_contract()
t[1][1][1][1]
display(m)
(lam_w, U_i_w) = tf.linalg.eigh(m)
display(lam_w.numpy())
display(U_i_w[:, 0].numpy())
display(tf.reshape(U_i_w[:, 0], [2]*num)[0][0])


n= 4


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-2.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.],
       [ 0.,  0.,  2.,  0.],
       [ 0.,  0.,  0., -2.]], dtype=float32)>

array([-2., -2.,  2.,  2.], dtype=float32)

array([1., 0., 0., 0.], dtype=float32)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [2]:
import tensorflow as tf
a = tf.constant([[[1]]])

In [6]:
a[0:1]

<tf.Tensor: shape=(1, 1, 1), dtype=int32, numpy=array([[[1]]], dtype=int32)>