In [9]:
! ls ../pytn
import sys
sys.path.append("..")

__init__.py   ctmrg_test.py mpo.py        mps_test.py
__pycache__   dmrg.py       mpo_test.py   utils.py
ctmrg.py      dmrg_test.py  mps.py


In [74]:
import tensorflow as tf
import numpy as np

In [65]:
import importlib
import pytn
import pytn.mpo
importlib.reload(pytn.mpo)

<module 'pytn.mpo' from '../pytn/mpo.py'>

In [73]:
num = 2
mpo = pytn.mpo.traverse_field_ising_mpo(J=2.0, g=0.0, num=num)
m = mpo.as_matrix()
t = mpo.full_contract()
t[1][1][1][1]
display(m)
(lam_w, U_i_w) = tf.linalg.eigh(m)
display(lam_w.numpy())
display(U_i_w[:, 0].numpy())
display(tf.reshape(U_i_w[:, 0], [2]*num)[0][0])


n= 4


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-2.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.],
       [ 0.,  0.,  2.,  0.],
       [ 0.,  0.,  0., -2.]], dtype=float32)>

array([-2., -2.,  2.,  2.], dtype=float32)

array([1., 0., 0., 0.], dtype=float32)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [76]:
num = 5
mpo = pytn.mpo.traverse_field_ising_mpo(J=1.0, g=1.0, num=num)
m = mpo.as_matrix()
t = mpo.full_contract()
(lam_w, U_i_w) = tf.linalg.eigh(m)
display(lam_w.numpy())
display(U_i_w[:, 0].numpy())

n= 32


array([-6.026683  , -5.457426  , -4.365017  , -3.7957637 , -3.4072394 ,
       -2.8379707 , -2.6616597 , -2.1887026 , -2.0924022 , -1.7455719 ,
       -1.6194444 , -1.1763123 , -0.9999997 , -0.5270423 , -0.4307403 ,
       -0.04221711,  0.04221736,  0.43074086,  0.5270428 ,  1.0000001 ,
        1.1763119 ,  1.6194437 ,  1.7455717 ,  2.0923996 ,  2.188706  ,
        2.6616595 ,  2.837972  ,  3.4072375 ,  3.7957628 ,  4.3650103 ,
        5.457431  ,  6.0266924 ], dtype=float32)

array([0.43696758, 0.22770771, 0.1457991 , 0.18918698, 0.13857833,
       0.08665611, 0.11244369, 0.18918765, 0.14579912, 0.08149052,
       0.05859531, 0.08665629, 0.11244365, 0.08149082, 0.12260533,
       0.22770973, 0.22770792, 0.12260466, 0.08149057, 0.11244372,
       0.08665609, 0.0585954 , 0.08149082, 0.1458002 , 0.18918708,
       0.11244375, 0.08665635, 0.13857934, 0.18918766, 0.14580022,
       0.22770968, 0.43697235], dtype=float32)

In [2]:
import tensorflow as tf
a = tf.constant([[[1]]])

In [6]:
a[0:1]

<tf.Tensor: shape=(1, 1, 1), dtype=int32, numpy=array([[[1]]], dtype=int32)>